// Mocks generated by Mockito 5.4.4 from annotations
// in madang_app/test/data/api/api_services_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:http/http.dart' as _i2;
import 'package:madang_app/data/api/api_services.dart' as _i7;
import 'package:madang_app/data/model/restaurant_detail_response.dart' as _i4;
import 'package:madang_app/data/model/restaurant_list_response.dart' as _i3;
import 'package:madang_app/data/model/restaurant_reviews_response.dart' as _i6;
import 'package:madang_app/data/model/restaurant_search_response.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRestaurantsResponse_1 extends _i1.SmartFake
    implements _i3.RestaurantsResponse {
  _FakeRestaurantsResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDetailRestaurantResponse_2 extends _i1.SmartFake
    implements _i4.DetailRestaurantResponse {
  _FakeDetailRestaurantResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchRestaurantsResponse_3 extends _i1.SmartFake
    implements _i5.SearchRestaurantsResponse {
  _FakeSearchRestaurantsResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReviewsResponse_4 extends _i1.SmartFake
    implements _i6.ReviewsResponse {
  _FakeReviewsResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServices extends _i1.Mock implements _i7.ApiServices {
  MockApiServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  set client(_i2.Client? _client) => super.noSuchMethod(
        Invocation.setter(
          #client,
          _client,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i3.RestaurantsResponse> getRestaurants() => (super.noSuchMethod(
        Invocation.method(
          #getRestaurants,
          [],
        ),
        returnValue: _i8.Future<_i3.RestaurantsResponse>.value(
            _FakeRestaurantsResponse_1(
          this,
          Invocation.method(
            #getRestaurants,
            [],
          ),
        )),
      ) as _i8.Future<_i3.RestaurantsResponse>);

  @override
  _i8.Future<_i4.DetailRestaurantResponse> getDetailRestaurant(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailRestaurant,
          [id],
        ),
        returnValue: _i8.Future<_i4.DetailRestaurantResponse>.value(
            _FakeDetailRestaurantResponse_2(
          this,
          Invocation.method(
            #getDetailRestaurant,
            [id],
          ),
        )),
      ) as _i8.Future<_i4.DetailRestaurantResponse>);

  @override
  _i8.Future<_i5.SearchRestaurantsResponse> searchRestaurants(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRestaurants,
          [query],
        ),
        returnValue: _i8.Future<_i5.SearchRestaurantsResponse>.value(
            _FakeSearchRestaurantsResponse_3(
          this,
          Invocation.method(
            #searchRestaurants,
            [query],
          ),
        )),
      ) as _i8.Future<_i5.SearchRestaurantsResponse>);

  @override
  _i8.Future<_i6.ReviewsResponse> postReviews(
    String? review,
    String? name,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postReviews,
          [
            review,
            name,
            id,
          ],
        ),
        returnValue:
            _i8.Future<_i6.ReviewsResponse>.value(_FakeReviewsResponse_4(
          this,
          Invocation.method(
            #postReviews,
            [
              review,
              name,
              id,
            ],
          ),
        )),
      ) as _i8.Future<_i6.ReviewsResponse>);
}
